### PR TITLE
Update react native per Snyk

### PR DESCRIPTION
**Pull request by swcurran**
Signed-off-by: Stephen Curran <swcurran@gmail.com>

### CODE REVIEW

**Comment by swcurran** [comment]
Equivalent to #294 but with DCO signoff.

**Comment by swcurran** [comment]
Also #287 #288.

**Comment by swcurran** [comment]
Some of the tests (windows, android) failing because they want higher versions of rust — current 1.65, Windows wants 1.66 (see below), while Android wants 1.70 or higher.

What needs to be done?

```
error: package `relative-path v1.9.2` cannot be built because it requires rustc 1.66 or newer, while the currently active rustc version is 1.65.0
Either upgrade to rustc 1.66 or newer, or use
cargo update -p relative-path@1.9.2 --precise ver
where `ver` is the latest version of `relative-path` supporting rustc 1.65.0
Error: Process completed with exit code 1.

```

**Comment by TimoGlastra** [comment]
@berendsliedrecht @andrewwhitehead can one of you rust magicians take a look at why there are errors with the rust version?

**Comment by swcurran** [comment]
Progress - but still not working.  Now the issue seems to be a `frozen-lockfile` setting?  @berendsliedrecht @andrewwhitehead — can one of you do what is needed to address the issue?

```
1s
Run pnpm install
  pnpm install
  shell: /usr/bin/bash -e {0}
  env:
    RUST_VERSION: stable 6 months ago
    CROSS_VERSION: 0.2.4
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
Scope: all 5 workspace projects
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with packages/anoncreds-react-native-example/package.json

Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"

    Failure reason:
    specifiers in the lockfile ({"@hyperledger/anoncreds-react-native":"workspace:*","expo":"~49.0.10","expo-splash-screen":"~0.24.0","expo-status-bar":"~1.9.0","react":"18.2.0","react-native":"0.72.7","@babel/core":"^7.20.0","@babel/runtime":"^7.22.15","@types/react":"~18.2.14"}) don't match specs in package.json ({"@babel/core":"^7.20.0","@babel/runtime":"^7.22.15","@types/react":"~18.2.14","@hyperledger/anoncreds-react-native":"workspace:*","expo":"~49.0.10","expo-status-bar":"~1.10.0","react":"18.2.0","react-native":"0.73.0","expo-splash-screen":"~0.25.0"})
Error: Process completed with exit code 1.
```

**Comment by swcurran** [comment]
Closing this — can’t see how to update the branch to include main updates.

**Pull request closed without merging**
