### PR TITLE
chore(js): update version to 0.2.3

### PR DESCRIPTION
**Pull request by TimoGlastra**
Update version so we can release https://github.com/hyperledger/anoncreds-rs/pull/338

### CODE REVIEW

**Comment by swcurran** [comment]
Hey @TimoGlastra — what should happen with the error in the wrapper testing?  Fix something?  Weird looking error messages, but presumably all stemming from the same thing?

**Review by berendsliedrecht — APPROVED** [review]
Think you have to run prettier :).

**Comment by TimoGlastra** [comment]
Running prettier /lint locally does not give the same error

**Comment by berendsliedrecht** [comment]
> Running prettier /lint locally does not give the same error

Different versions? Not sure what else it could be.

**Review by genaris — APPROVED** [review]
Working now I've upgraded pnpm version to 9 in CI

**Pull request merged**
