### PR TITLE
Deal with snyk notifications for react-native -- by updating to latest of all dependencies

### PR DESCRIPTION
**Pull request by swcurran**
In making this PR, I looked up the latest versions of each of the called out in the Snyk report and used that.  We'll see how that goes.

### CODE REVIEW

**Comment by swcurran** [comment]
@berendsliedrecht — can you please review this PR. Please note that I didn’t run any tests on this — I just updated the three components in the two package.json files to their most recent versions per NPM.  I did not verify that the updated dependencies won’t break anything.   I know — bad way to do things, but I don’t really know how to run the react-native wrapper/example.

Thanks!

**Comment by berendsliedrecht** [comment]
@swcurran could you delete the `package-lock.json`? It is created when running `npm install`, but we use `pnpm` only.

**Comment by swcurran** [comment]
Done — thanks!

**Comment by swcurran** [comment]
@berendsliedrecht — bump -- looks like this is ready.

**Review by berendsliedrecht — APPROVED** [review]

**Comment by swcurran** [comment]
@andrewwhitehead — the post merge Lint task failed — https://github.com/hyperledger/anoncreds-rs/actions/runs/8031489343/job/21939863984. Could you please take a look and see what is to be done?  Is it an issue or sunspots?

**Pull request merged**
